apiVersion: v1
kind: ConfigMap
metadata:
  name: normal-ass-note-config
  namespace: normal-ass-note
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "normal-ass-note"
  Jwt__Audience: "normal-ass-note-client"
