apiVersion: v1
kind: Secret
metadata:
  name: normal-ass-note-secret
  namespace: normal-ass-note
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=192.168.63.218;Port=5432;Database=normal_ass_note;Username=quangsumi;Password=dbpassword9090"
  Jwt__SigningKey: "development-only-signing-key-change-this-before-production"
